name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
    
    - name: Run tests
      run: pytest tests/
      
    - name: Run main script
      run: python src/main.py

    - name: List files
      run: |
        pwd
        ls -R  

    - name: Archive and Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ml_pipeline-artifacts
        path: ${{ github.workspace }}/results

    - name: Save to repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN2 }}
      run: |
        echo GH_TOKEN: "${GH_TOKEN2}"
        git config --global user.name 'github-actions'
        git config --local user.email "action@github.com"
        git add .
        git commit -m "Add results"
        git push

    
       
